### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by callmeEthan** [malordin/steamdeck-samba-server#2]
The setup completed, but other devices on the network can't connect. Only the steam deck itself can connect to the smb server.

**Comment by malordin** [comment]
Hi! Perhaps NetBIOS name does not work, try to access the steam deck from your PC by ip address, for example 

`\\192.168.1.100`

You must first know the ip address of the steam deck, it can be done from the console in desktop mode by typing the command:

`ip a`

Or go to the connection settings and find information about wi-fi or wired connection, there should be a line "IP address"

**Comment by callmeEthan** [comment]
Yes I also tried that. I previously used ftp://192.168.1.14 which work fine. But want to change to smb for convenient.
accessing `\\192.168.1.14` only return 'windows cannot access ip' code 0x80004005.
I tried to reinstall it, here is the output.
```
(deck@steamdeck ~)$ sh -c "$(curl -fsSL https://raw.githubusercontent.com/malordin/steamdeck-samba-server/main/script.sh)"
WARNING: This script will install Samba server on your system.
Did you change the password via passwd? [Y/N] y
Please enter your password: [sudo] password for deck: Continuing with Samba server installation...
Disabling steamos-readonly...
Editing pacman.conf file...
Populating pacman keys...
==> Appending keys from archlinux.gpg...
==> Updating trust database...
gpg: next trustdb check due at 2023-10-27
Initializing pacman keys...
Installing samba...
:: Synchronizing package databases...
 jupiter-main                106.1 KiB  43.4 KiB/s 00:02 [##############################] 100%
 holo-main                    51.1 KiB  29.0 KiB/s 00:02 [##############################] 100%
 core-main is up to date
 extra-main is up to date
 community-main is up to date
 multilib-main is up to date
resolving dependencies...
looking for conflicting packages...

Packages (2) liburing-2.4-1  samba-4.18.3-1

Total Installed Size:  56.71 MiB

:: Proceed with installation? [Y/n]
(2/2) checking keys in keyring                                                                [#######################################################] 100%
(2/2) checking package integrity                                                              [#######################################################] 100%
(2/2) loading package files                                                                   [#######################################################] 100%
(2/2) checking for file conflicts                        [##############################] 100%[###########################----------------------------]  50%
(2/2) checking available disk space                      [##############################] 100%
:: Processing package changes...
(1/2) installing liburing                                [##############################] 100%
(2/2) installing samba                                   [##############################] 100%
Optional dependencies for samba
    python-dnspython: netads_dns.py, dnsresolver.py and traffic_packets.py
    python-markdown: ms_schema_markdown.py and ms_forest_updates_markdown.py
    python-cryptography: lockout_tests.py gp_cert_auto_enroll_ext.py gpo.py and kcrypto.py
:: Running post-transaction hooks...
(1/3) Reloading system manager configuration...
(2/3) Creating temporary files...
/usr/lib/tmpfiles.d/steamos.conf:6: Duplicate line for path "/root", ignoring.
/usr/lib/tmpfiles.d/steamos.conf:23: Duplicate line for path "/var/empty", ignoring.
/usr/lib/tmpfiles.d/tmp.conf:12: Duplicate line for path "/var/tmp", ignoring.
/usr/lib/tmpfiles.d/var.conf:19: Duplicate line for path "/var/cache", ignoring.
(3/3) Arming ConditionNeedsUpdate...
Adding 'deck' user to samba user database...
New SMB password:
Retype new SMB password:
Enabling and starting smb service...
Writing new smb.conf file...
Restarting smb service...
Filesystem now read-only
Samba server set up successfully! You can access the 'steamapps', 'downloads' and 'mmcblk0p1' folders on your Steam Deck from any device on your local network.
Press Enter to continue...
```

**Comment by malordin** [comment]
The script works fine if you look at the logs. I believe there is a problem with Windows. 

Try enabling guest access in local group policy via gpedit.msc at the following path:

**`Computer configuration > administrative templates > network > Lanman Workstation: "Enable insecure guest logons" = Enabled`**

[Screenshot](https://www.k-max.name/wp-content/uploads/2021/01/gpedit-insecure-logons.png)

Then reboot and try again.

Try to enter the `\\ip address` in Windows Explorer, you should be asked for login and password. I had a problem that if I didn't check the "remember me" box, the login didn't work, so try leaving it on and enter "deck" as the login and the password as the one you entered when you ran the script.

If your Windows edition does not allow you to run gpedit.msc, you can fix the situation using the console. Try running the console as administrator and run this:

`reg add "HKLM\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v AllowInsecureGuestAuth /t REG_DWORD /d 1`

And reboot.

After all this please post here, either way it will help or not, I'll be waiting for an answer, thanks!

**Comment by callmeEthan** [comment]
I tried your suggestion but it's still doesn't work...
Its not just my PC either, I also use my (android) phone to access my windows smb server, but it can't connect to steam deck either. `smb://192.168.1.14` returns 'host unreachable'. Only the deck can access it's own smb server.

**Comment by callmeEthan** [comment]
I looked around and got it working, turn out it was the system firewall. I ran these command:
```
firewall-cmd --permanent --zone=public --add-service=samba
firewall-cmd --reload
```
And is now able to access steamdeck's smb server from other devices, even in game mode. They were on by default I suppose.

**Comment by ndouglas** [comment]
Same experience, @callmeEthan. Thank you for reporting what you learned.
