### ISSUE TITLE
folders have write protection now

### ISSUE THREAD

**Issue by habanerochilly** [malordin/steamdeck-samba-server#5]
after using the promt, the 3 folders now have write protection and i cant change it back.

how do i reverse the  promt?

**Comment by malordin** [comment]
Hello!

I don't really understand how this can be related, as the script doesn't interact with folders in any way. The samba service interacts with folders, try disabling it manually:

```
sudo systemctl service stop smb
sudo systemctl service disable smb
```

**Comment by Double-0-seven7** [comment]
> Hello!
> 
> I don't really understand how this can be related, as the script doesn't interact with folders in any way. The samba service interacts with folders, try disabling it manually:
> 
> ```
> sudo systemctl service stop smb
> sudo systemctl service disable smb
> ```

@malordin unrelated but on steam os 3.5.5 stable you now need to open the samba ports so other devices could connect to your share.
I had to enable the firewall and allow incoming connection for samba but there may be another way for this.
May wanna change your script (or not if its a bug and would get fixed later on).

**Comment by malordin** [comment]
> you now need to open the samba ports so other devices could connect to

Yeah, that's what happened, my steam deck didn't have firewall for some reason, even though I put all the updates. Now after a complete reinstallation it is there. I updated the script so it now opens ports via firewall-cmd.

Thank you @Double-0-seven7 !
